name: Collect tweets

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - 'config.yml'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "24 4/6 * * *"

jobs:
  collect:
    environment: default
    permissions:
      id-token: write
      pages: write
      contents: write
    concurrency:
      group: "automation"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch submodules
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STATE_SSH_KEY }}'
          git submodule update --remote --init --recursive
          git submodule foreach --recursive git config --local http.https://github.com/.extraheader "$(git config --local http.https://github.com/.extraheader)"
          cd state && git checkout main
      - name: Setup Go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Collect tweets
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          go run github.com/Ukraine-DAO/twitter-threads/collect --config config.yml --state state/state.json
      - name: Commit updated state
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.STATE_SSH_KEY }}'
          cd state
          git config user.name automation
          git config user.email github-actions@github.com
          git add state.json
          if ! git diff-index --quiet HEAD; then
            git commit -m 'Update state'
            git push
          fi
